apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
spec:
  selector:
    matchLabels:
      app: app3
  replicas: 1
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: danipe1970/app3:v0
          #image: paulbouwer/hello-kubernetes:1.10
          env:
          - name: MESSAGE
            value: "Hello from app3."
          #imagePullPolicy: Always
          ports:
            - containerPort: 80
            #- containerPort: 8080
