# docker build -t dockerize-vuejs-app .
# docker run -it -p 8080:80 --rm --name vuejs-app-1 dockerize-vuejs-app

FROM node:16.20.2-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.13.12-alpine as production-stage
COPY --from=build-stage app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]